name: Node.js CI

on:
  push:
    branches: 
      - main
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.x'
      - next
      - next-major
      - alpha
      - beta
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.x'
      - next
      - next-major
      - alpha
      - beta

concurrency:
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  publish:

    if: github.ref_name == 'main'

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@eslint-reasonable'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile --prefer-offline --reporter=append-only
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: release"
          publish: "pnpm run ci:publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}